test to confirm if variable-based flag is the issue
Signed-off-by: Duncan Ragsdale <88173870+Thistleman@users.noreply.github.com>

diff --git a/subcommands/gridlabd-template b/subcommands/gridlabd-template
--- a/subcommands/gridlabd-template
+++ b/subcommands/gridlabd-template
@@ -8,21 +8,17 @@ if [ ${GLD_ETC:-none} == none ]; then
     export GLD_ETC=${gridlabd --version=install}/shared/gridlabd
 fi
 
-echo "Here: '${GITHUB_TOKEN}'"
 export GITHUB_TOKEN=$(gridlabd-git token $GITHUB_TOKEN)
 
 # check for github api token and set header if defined
 if [ ${GITHUB_TOKEN:-none} != none ]; then
     echo "Token defined from GITHUB_TOKEN set in config."
     echo "To change your token, run: gridlabd template config set GITHUB_TOKEN <your-value>"
-    export GLD_GIT_HEADER='--header "Authorization: token '$GITHUB_TOKEN'"'
 else
     echo "API token not provided."
     echo "Set your token using: gridlabd template config set GITHUB_TOKEN <your-value>"
     echo "Default github rate limits will apply."
 fi
-
-printenv
 
 # configurable parameters
 GITHUB="https://github.com"
@@ -169,7 +165,7 @@ function fetch_index()
     fi
     if [ ! -f "$INDEX" ]; then
         debug "downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ} (curl -sL $GITFILE/$ORGANIZATION/.index)... "
-        curl $GLD_GIT_HEADER -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
+        curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
     fi
     if [ ! -f "$INDEX" ]; then
         error 1 "unable to fetch index"
@@ -298,14 +294,14 @@ function get()
         DSTDIR="$GLD_ETC/template/$ORGANIZATION/$TEMPLATE"
         mkdir -p $DSTDIR
         debug "looking for catalog in $SRCDIR/.catalog"
-        CATALOG=$(curl $GLD_GIT_HEADER -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
+        CATALOG=$(curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
         if [ -z "$CATALOG" ]; then
             verbose "no catalog found; extracting legacy template from $GITFILE/$ORGANIZATION/$TEMPLATE.zip"
-            (curl $GLD_GIT_HEADER -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
+            (curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
         else
             verbose "downloading template from $SRCDIR/.catalog: $(echo $CATALOG | tr -c 'A-Za-z_.' ' ')"
             for FILE in $CATALOG; do
-                curl $GLD_GIT_HEADER -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
+                curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
                 debug "catalog file $FILE ok"
             done
             test -f "$DSTDIR/$TEMPLATE.md" || warning "no documentation found"
@@ -509,7 +505,7 @@ done
 CACHEDIR="$DATADIR/.gridlabd-template"
 GITPROJ="$GITHUB/$GITUSER/$GITREPO"
 GITFILE="$GITHUBUSERCONTENT/$GITUSER/$GITREPO/$GITBRANCH"
-COMMIT_INFO=$(curl $GLD_GIT_HEADER -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
+COMMIT_INFO=$(curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
 COMMIT_ID=$(echo $COMMIT_INFO | gridlabd json-get commit sha 2>/dev/null || error 1 $(echo $COMMIT_INFO | gridlabd json-get message 2>/dev/null))
 INDEX=$CACHEDIR/$COMMIT_ID
 
