Update gridlabd-marimo

diff --git a/subcommands/gridlabd-marimo b/subcommands/gridlabd-marimo
--- a/subcommands/gridlabd-marimo
+++ b/subcommands/gridlabd-marimo
@@ -31,7 +31,6 @@
 ## See also:
 ## 
 ## * https://github.com/arras-energy/marimo
-##
 ## * https://docs.marimo.io/
 ## 
 
@@ -53,7 +52,16 @@ function error()
     # Display an error message and optionally exit with EXITCODE
     #
     echo "ERROR: $1" > /dev/stderr
-    test -z "$2" || exit $2
+    test -z "$2" || exit $(eval 'echo $'$2)
+}
+
+function warning()
+{
+    # warning MESSAGE
+    #
+    # Display a warning message and optionally exit with EXITCODE
+    #
+    echo "WARNING: $1" > /dev/stderr    
 }
 
 function index()
@@ -97,7 +105,7 @@ function download()
     EXE=$LIB/$1.py
     ETAG=$LIB/.etag/$1
     if [ ! -f $EXE -a -z "$(index | grep $1)" ]; then
-        error "no such notebook published" $E_NOTFOUND
+        error "no such notebook published" E_NOTFOUND
     fi
     if [ -f $ETAG ]; then
         curl -sL --etag-compare $ETAG --etag-save $ETAG $URL/$1.py > $EXE 2>>$LOG
@@ -107,7 +115,7 @@ function download()
     if [ $? -ne 0 ]; then
         cat $EXE >>$LOG
         rm -f $EXE $ETAG 2>>$LOG
-        error "unable to download '$1'" $E_FAIL
+        error "unable to download '$1'" E_FAIL
     fi    
 }
 
@@ -115,7 +123,7 @@ function start()
 {
     EXE=$LIB/$1.py
     if [ ! -f $EXE ]; then
-        error "$1 not found" $E_NOTFOUND
+        error "$1 not found" E_NOTFOUND
     fi
     if [ $WAIT == no ]; then
         marimo run $EXE 1>>$LOG 2>&1 &
@@ -134,11 +142,11 @@ echo "*** COMMAND = '$0 $*' ***" >>$LOG
 
 if [ $# -eq 0 ]; then
     grep '^## ' $0 | cut -c4-
-    exit 0
+    exit $E_SYNTAX
 fi
 
 if [ -z "$GLD_ETC" ]; then
-    error "missing gridlabd environment" $E_MISSING
+    error "missing gridlabd environment" E_MISSING
 fi
 
 while [ $# -gt 0 ]; do
@@ -148,7 +156,7 @@ while [ $# -gt 0 ]; do
             ;;
         --help|-h|help)
             cat $0 | grep '^## ' | cut -c4-
-            exit E_OK
+            exit $E_OK
             ;;
         --pid)
             getpid $2
@@ -169,10 +177,6 @@ while [ $# -gt 0 ]; do
             ;;
         list) # list of active apps
             getlist
-            # PIDLIST=$(getlist)
-            # for PID in $PIDLIST; do
-            #     getinfo $PID
-            # done
             ;;
         stop)
             PID=$(getpid $2)
@@ -182,7 +186,7 @@ while [ $# -gt 0 ]; do
             shift 1
             ;;
         -*)
-            error "option '$1' is invalid" $E_SYNTAX
+            error "option '$1' is invalid" E_SYNTAX
             ;;
         *)
             LOC=$(geturl $1)
