Update gridlabd-marimo

diff --git a/subcommands/gridlabd-marimo b/subcommands/gridlabd-marimo
--- a/subcommands/gridlabd-marimo
+++ b/subcommands/gridlabd-marimo
@@ -1,28 +1,198 @@
 #!/bin/bash
-## Syntax: gridlabd marimo NAME
+## Syntax: gridlabd marimo [OPTIONS ...] [COMMAND] [NOTEBOOK]
 ## 
-## Run marimo in gridlabd environment.
+## Options:
 ## 
+##   `--debug`: send log to /dev/stderr
+## 
+##   `-h|--help|help`: get this help
+## 
+##   `--pid`: get the process id for the notebook (if any)
+## 
+##   `--url`: get the URL for the notebook (if any)
+## 
+##   `--verbose`: echo script to stderr
+## 
+##   `--wait`: wait for marimo server to exit
+## 
+## Commands:
+## 
+##   `index`: get list of available notebooks that can be downloaded
+## 
+##   `list`: list open marimo notebooks
+## 
+##   `stop`: stops the marimo notebook
+## 
+## Run a gridlabd marimo notebook.
+## 
+## GridLAB-D marimo notebooks are distributed from the GitHub arras-energy
+## repository `marimo`.
+##
+## See also:
+## 
+## * https://github.com/arras-energy/marimo
+##
+## * https://docs.marimo.io/
+## 
+
+LIB=$GLD_ETC/marimo
+LOG=$LIB/marimo.log
+URL=https://raw.githubusercontent.com/arras-energy/marimo/refs/heads/main/source
+WAIT=no
+
+E_OK=0
+E_SYNTAX=1
+E_FAIL=2
+E_NOTFOUND=3
+E_MISSING=4
+
+function error()
+{
+    # error MESSAGE [EXITCODE]
+    #
+    # Display an error message and optionally exit with EXITCODE
+    #
+    echo "ERROR: $1" > /dev/stderr
+    test -z "$2" || exit $2
+}
+
+function index()
+{
+    # index
+    #
+    # Display a list of available notebooks online
+    #
+    curl -sL $URL/.index 2>>$LOG
+}
+
+function getlist()
+{
+    basename -s .py $(ps -ax | grep bin/marimo | grep -v grep | sed -r 's/ +/ /g' | cut -f7 -d' ') 2>>$LOG
+}
+
+function getpid()
+{
+    EXE=$LIB/$1.py
+    ps ax | grep bin/marimo | grep $EXE | cut -f1 -d' ' 2>>$LOG
+}
+
+function getinfo()
+{
+    for PID in $*; do
+        lsof -i -P -a -p $PID | tail -n +1 2>>$LOG
+    done
+}
+
+function geturl()
+{
+    PID=$(getpid $1)
+    if [ ! -z "$PID" ]; then
+        LOC=$(lsof -i -P -a -p $PID | grep '(LISTEN)' | sed -r 's/ +/ /g' | cut -f9 -d' ' 2>>$LOG)
+        echo "http://$LOC/"
+    fi
+}
+
+function download()
+{
+    EXE=$LIB/$1.py
+    ETAG=$LIB/.etag/$1
+    if [ ! -f $EXE -a -z "$(index | grep $1)" ]; then
+        error "no such notebook published" $E_NOTFOUND
+    fi
+    if [ -f $ETAG ]; then
+        curl -sL --etag-compare $ETAG --etag-save $ETAG $URL/$1.py > $EXE 2>>$LOG
+    else
+        curl -sL --etag-save $ETAG $URL/$1.py > $EXE 2>>$LOG
+    fi
+    if [ $? -ne 0 ]; then
+        cat $EXE >>$LOG
+        rm -f $EXE $ETAG 2>>$LOG
+        error "unable to download '$1'" $E_FAIL
+    fi    
+}
+
+function start()
+{
+    EXE=$LIB/$1.py
+    if [ ! -f $EXE ]; then
+        error "$1 not found" $E_NOTFOUND
+    fi
+    if [ $WAIT == no ]; then
+        marimo run $EXE 1>>$LOG 2>&1 &
+    else
+        marimo run $EXE 2>>$LOG
+    fi
+}
+
+function stop()
+{
+    echo ""
+}
+
+mkdir -p $LIB/.etag
+echo "*** COMMAND = '$0 $*' ***" >>$LOG
 
 if [ $# -eq 0 ]; then
     grep '^## ' $0 | cut -c4-
     exit 0
 fi
 
-DIR=$GLD_ETC/marimo
-EXE=$DIR/$1.py
-if [ ! -d $DIR ]; then
-    mkdir $DIR
+if [ -z "$GLD_ETC" ]; then
+    error "missing gridlabd environment" $E_MISSING
 fi
 
-if [ ! -f $EXE ]; then
-    SOURCE=$($GLD_BIN/gridlabd.bin --version=origin | cut -f4- -d/)
-    curl -sL https://raw.githubusercontent.com/arras-energy/marimo/refs/heads/main/source/$1.py > $EXE
-    if [ $? -ne 0 ]; then
-        rm -f $EXE
-        echo "$1 not found"
-        exit 1
-    fi
-fi
-
-marimo run $EXE
+while [ $# -gt 0 ]; do
+    case $1 in
+        --debug)
+            LOG=/dev/stderr
+            ;;
+        --help|-h|help)
+            cat $0 | grep '^## ' | cut -c4-
+            exit E_OK
+            ;;
+        --pid)
+            getpid $2
+            shift 1
+            ;;
+        --url)
+            geturl $2
+            shift 1
+            ;;
+        --verbose)
+            set -x
+            ;;
+        --wait)
+            WAIT=yes
+            ;;
+        index) # list of available apps
+            index
+            ;;
+        list) # list of active apps
+            getlist
+            # PIDLIST=$(getlist)
+            # for PID in $PIDLIST; do
+            #     getinfo $PID
+            # done
+            ;;
+        stop)
+            PID=$(getpid $2)
+            if [ ! -z "$PID" ]; then
+                kill $PID
+            fi
+            shift 1
+            ;;
+        -*)
+            error "option '$1' is invalid" $E_SYNTAX
+            ;;
+        *)
+            LOC=$(geturl $1)
+            if [ -z "$LOC" ]; then
+                download $1
+                start $1
+            else
+                open $LOC
+            fi
+            ;;
+    esac
+    shift 1
+done
