ah, the use of sudo in ubuntu is no longer needed and creates env issues. Looks like we need to fix undefined token issue though?
Signed-off-by: Duncan Ragsdale <88173870+Thistleman@users.noreply.github.com>

diff --git a/subcommands/gridlabd-template b/subcommands/gridlabd-template
--- a/subcommands/gridlabd-template
+++ b/subcommands/gridlabd-template
@@ -10,14 +10,15 @@ fi
 
 export GITHUB_TOKEN=$(gridlabd-git token $GITHUB_TOKEN)
 
+# NOTE: Validation won't properly display syntax or variable errors in curl calls. Manually call "gridlabd template config reset" or any other call to see script outputs, curl returned errors and warnings.
+# This is doubly true when identifying issues in the github actions runner.
+
 # check for github api token and set header if defined
 if [ ${GITHUB_TOKEN:-none} != none ]; then
-    echo "Token defined from GITHUB_TOKEN set in config."
-    echo "To change your token, run: gridlabd template config set GITHUB_TOKEN <your-value>"
+    echo "Token defined."
 else
     echo "API token not provided."
-    echo "Set your token using: gridlabd template config set GITHUB_TOKEN <your-value>"
-    echo "Default github rate limits will apply."
+    echo "Use 'GITHUB_TOKEN=<your-token>' or write your token to a file in '~/.github/access-token' "
 fi
 
 # configurable parameters
@@ -165,7 +166,7 @@ function fetch_index()
     fi
     if [ ! -f "$INDEX" ]; then
         debug "downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ} (curl -sL $GITFILE/$ORGANIZATION/.index)... "
-        curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
+        curl --header "authorization: Bearer $GITHUB_TOKEN" -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
     fi
     if [ ! -f "$INDEX" ]; then
         error 1 "unable to fetch index"
@@ -294,14 +295,14 @@ function get()
         DSTDIR="$GLD_ETC/template/$ORGANIZATION/$TEMPLATE"
         mkdir -p $DSTDIR
         debug "looking for catalog in $SRCDIR/.catalog"
-        CATALOG=$(curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
+        CATALOG=$(curl --header "authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
         if [ -z "$CATALOG" ]; then
             verbose "no catalog found; extracting legacy template from $GITFILE/$ORGANIZATION/$TEMPLATE.zip"
-            (curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
+            (curl --header "authorization: Bearer $GITHUB_TOKEN" -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
         else
             verbose "downloading template from $SRCDIR/.catalog: $(echo $CATALOG | tr -c 'A-Za-z_.' ' ')"
             for FILE in $CATALOG; do
-                curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
+                curl --header "authorization: Bearer $GITHUB_TOKEN" -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
                 debug "catalog file $FILE ok"
             done
             test -f "$DSTDIR/$TEMPLATE.md" || warning "no documentation found"
@@ -505,7 +506,7 @@ done
 CACHEDIR="$DATADIR/.gridlabd-template"
 GITPROJ="$GITHUB/$GITUSER/$GITREPO"
 GITFILE="$GITHUBUSERCONTENT/$GITUSER/$GITREPO/$GITBRANCH"
-COMMIT_INFO=$(curl --header "Authorization: Bearer $GITHUB_TOKEN" -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
+COMMIT_INFO=$(curl --header "authorization: Bearer $GITHUB_TOKEN" -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
 COMMIT_ID=$(echo $COMMIT_INFO | gridlabd json-get commit sha 2>/dev/null || error 1 $(echo $COMMIT_INFO | gridlabd json-get message 2>/dev/null))
 INDEX=$CACHEDIR/$COMMIT_ID
 
