Fix master deploy failures (#325)
Signed-off-by: Duncan Ragsdale <88173870+Thistleman@users.noreply.github.com>

diff --git a/subcommands/gridlabd-template b/subcommands/gridlabd-template
--- a/subcommands/gridlabd-template
+++ b/subcommands/gridlabd-template
@@ -8,6 +8,19 @@ if [ ${GLD_ETC:-none} == none ]; then
     export GLD_ETC=${gridlabd --version=install}/shared/gridlabd
 fi
 
+export GITHUB_TOKEN=$(gridlabd-git token $GITHUB_TOKEN)
+
+# NOTE: Validation won't properly display syntax or variable errors in curl calls. Manually call "gridlabd template config reset" or any other call to see script outputs, curl returned errors and warnings.
+# This is doubly true when identifying issues in the github actions runner.
+
+# check for github api token and set header if defined
+if [ ${GITHUB_TOKEN:-none} != none ]; then
+    echo "Token defined."
+else
+    echo "API token not provided."
+    echo "Use 'GITHUB_TOKEN=<your-token>' or write your token to a file in '~/.github/access-token' "
+fi
+
 # configurable parameters
 GITHUB="https://github.com"
 GITAPI="https://api.github.com"
@@ -79,6 +92,7 @@ function config()
             echo "    \"GITBRANCH\" : \"$GITBRANCH\","
             echo "    \"CACHEDIR\" : \"$CACHEDIR\","
             echo "    \"DATADIR\" : \"$DATADIR\","
+            echo "    \"GITHUB_TOKEN\" : \"$GITHUB_TOKEN\","
             echo "}"
         elif [ "$FORMAT" == "glm" ]; then
             debug "showing config in glm format"
@@ -90,6 +104,7 @@ function config()
             echo "#define TEMPLATE_GITBRANCH=$GITBRANCH"
             echo "#define TEMPLATE_CACHEDIR=$CACHEDIR"
             echo "#define TEMPLATE_DATADIR=$DATADIR"
+            echo "#define TEMPLATE_GITHUB_TOKEN=$GITHUB_TOKEN"
         elif [ "$FORMAT" == "csv" ]; then
             debug "showing config in csv format"
             echo "name,value"
@@ -101,6 +116,7 @@ function config()
             echo "GITBRANCH,\"$GITBRANCH\""
             echo "CACHEDIR,\"$CACHEDIR\""
             echo "DATADIR,\"$DATADIR\""
+            echo "GITHUB_TOKEN,\"$GITHUB_TOKEN\""
         else
             debug "showing config in raw format"
             echo "GITHUB=\"$GITHUB\""
@@ -111,6 +127,7 @@ function config()
             echo "GITBRANCH=\"$GITBRANCH\""
             echo "CACHEDIR=\"$CACHEDIR\""
             echo "DATADIR=\"$DATADIR\""
+            echo "GITHUB_TOKEN=\"$GITHUB_TOKEN\""
         fi
     elif [ "$1" == "reset" ]; then
         debug "resetting config"        
@@ -149,7 +166,7 @@ function fetch_index()
     fi
     if [ ! -f "$INDEX" ]; then
         debug "downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ} (curl -sL $GITFILE/$ORGANIZATION/.index)... "
-        curl -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
+        curl ${GITHUB_TOKEN:+ --header "authorization: Bearer $GITHUB_TOKEN"} -sL -f "$GITFILE/$ORGANIZATION/.index" >"$INDEX" || error 2 "index not found"
     fi
     if [ ! -f "$INDEX" ]; then
         error 1 "unable to fetch index"
@@ -278,14 +295,14 @@ function get()
         DSTDIR="$GLD_ETC/template/$ORGANIZATION/$TEMPLATE"
         mkdir -p $DSTDIR
         debug "looking for catalog in $SRCDIR/.catalog"
-        CATALOG=$(curl -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
+        CATALOG=$(curl ${GITHUB_TOKEN:+ --header "authorization: Bearer $GITHUB_TOKEN"} -sL -f "$SRCDIR/.catalog" "$DSTDIR" | grep -v '^#' | cut -f1 -d:) # || error 2 "missing template catalog")
         if [ -z "$CATALOG" ]; then
             verbose "no catalog found; extracting legacy template from $GITFILE/$ORGANIZATION/$TEMPLATE.zip"
-            (curl -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
+            (curl ${GITHUB_TOKEN:+ --header "authorization: Bearer $GITHUB_TOKEN"} -sL "$GITFILE/$ORGANIZATION/$TEMPLATE.zip" > "/tmp/$$.zip" && unzip -q -o -d "$GLD_ETC/template" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
         else
             verbose "downloading template from $SRCDIR/.catalog: $(echo $CATALOG | tr -c 'A-Za-z_.' ' ')"
             for FILE in $CATALOG; do
-                curl -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
+                curl ${GITHUB_TOKEN:+ --header "authorization: Bearer $GITHUB_TOKEN"} -sL -f "$SRCDIR/$FILE" > "$DSTDIR/$FILE" || error 2 "unable to download '$FILE'"
                 debug "catalog file $FILE ok"
             done
             test -f "$DSTDIR/$TEMPLATE.md" || warning "no documentation found"
@@ -489,7 +506,7 @@ done
 CACHEDIR="$DATADIR/.gridlabd-template"
 GITPROJ="$GITHUB/$GITUSER/$GITREPO"
 GITFILE="$GITHUBUSERCONTENT/$GITUSER/$GITREPO/$GITBRANCH"
-COMMIT_INFO=$(curl -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
+COMMIT_INFO=$(curl ${GITHUB_TOKEN:+ --header "authorization: Bearer $GITHUB_TOKEN"} -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH")
 COMMIT_ID=$(echo $COMMIT_INFO | gridlabd json-get commit sha 2>/dev/null || error 1 $(echo $COMMIT_INFO | gridlabd json-get message 2>/dev/null))
 INDEX=$CACHEDIR/$COMMIT_ID
 
